[build]
jobs = 6                    # Limit jobs to not saturate all cpus
target-dir = "../target"    # Force the same shared target directory for builds (rust-analyzer)

[alias]
perf-build = [
  "build", "--profile", "perf",
  "--config", "build.rustflags=[\"-C\",\"force-frame-pointers=yes\"]",
]